/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface ProviderPatch {
  /**
   * `"[REDACTED]"` → keep existing keyring secret; empty → clear; otherwise save.
   * @nullable
   */
  apiKey?: string | null
  /**
   * `undefined`/omitted = leave unchanged. `[]` = clear the list. Entries
   * are trimmed/empty-filtered on apply; duplicates are kept but logged.
   * @nullable
   */
  apiKeys?: string[] | null
  /** @nullable */
  baseUrl?: string | null
  id: string
}